@apiKey = {{$dotenv WX_API_KEY}}
@opURL = {{$dotenv OP_URL}}


### Get IAM Token
# @name login
POST https://iam.cloud.ibm.com/identity/token
Content-Type: application/x-www-form-urlencoded
Accept: application/json

grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey={{apiKey}}&response_type=cloud_iam

### Fetch Model by ID
@access_token = {{login.response.body.access_token}}
# @name fetch_model_id
POST {{opURL}}/opgrc/api/v2/query
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "statement": "SELECT [Model].[Resource ID] FROM [Model] WHERE [Name]='INST AskHR Chatbot'",
  "skipCount": 0
}

### Get Model Metric Definitions
# @name fetch_model_metrics
@model_id = {{fetch_model_id.response.body.rows[0].fields[0].value}}
POST {{opURL}}/opgrc/api/v2/query
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "statement": "SELECT [Metric].[Resource ID], [Metric].[Name], [Metric].[Description] FROM [Model] JOIN [Metric] ON PARENT([Model]) WHERE [Model].[Resource ID]={{model_id}}",
  "skipCount": 0
}


### Get MetricValue Type Definition
# @name get_metric_value_type_definition
GET {{opURL}}/opgrc/api/v2/types/MetricValue?includeFieldDefinitions
Authorization: Bearer {{access_token}}
Content-Type: application/json


### Get MetricValueId
# @name fetch_metric_value_id
@model_id = {{fetch_model_id.response.body.rows[0].fields[0].value}}
POST {{opURL}}/opgrc/api/v2/query
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "statement": "SELECT [MetricValue].[Resource ID], [MetricValue].[Name] FROM [MetricValue]  WHERE [Name]='Answer_relevance_MV_0000024'",
  "skipCount": 0
}

### Get MetricValueId
# @name fetch_metric_value_object
@metric_value_id = {{fetch_metric_value_id.response.body.rows[0].fields[0].value}}
GET {{opURL}}/opgrc/api/v2/contents/{{metric_value_id}}
Authorization: Bearer {{access_token}}
Content-Type: application/json


### GET MetricValue Object Template
# @name get_metric_value_object_template
GET {{opURL}}/opgrc/api/v2/contents/template?type_id=77
Authorization: Bearer {{access_token}}
Content-Type: application/json

### Create new metric value object
# @name create_metric_value_object
@answer_relevance_id = 10210
@metric_description = "Metric value for JVP EU Agentic RAG"
@metric_value = 0.75

POST {{opURL}}/opgrc/api/v2/contents
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "fields": [
    {
      "id": "1311",
      "data_type": "ENUM_TYPE",
      "name": "MRG-Metric-Shared:Breach Status",
      "value": {
        "id": "4184",
        "name": "Not Determined",
        "localized_label": "Not Determined",
        "index": 4,
        "hidden": false
      }
    },
    {
      "id": "1310",
      "data_type": "ENUM_TYPE",
      "name": "MRG-Metric-Shared:Collection Status",
      "value": {
        "id": "4166",
        "name": "Awaiting Collection",
        "localized_label": "Awaiting Collection",
        "index": 1,
        "hidden": false
      }
    },
    {
      "id": "1312",
      "data_type": "ENUM_TYPE",
      "name": "MRG-Metric-Shared:Direction Information"
    },
    {
      "id": "3060",
      "data_type": "FLOAT_TYPE",
      "name": "MRG-Metric-Shared:Lower Threshold"
    },
    {
      "id": "3113",
      "data_type": "FLOAT_TYPE",
      "name": "MRG-Metric-Shared:Maximum Value"
    },
    {
      "id": "1309",
      "data_type": "STRING_TYPE",
      "name": "MRG-Metric-Shared:Metric Capturer"
    },
    {
      "id": "1315",
      "data_type": "ENUM_TYPE",
      "name": "MRG-Metric-Shared:Metric Type",
      "value": {
        "id": "4169",
        "name": "Standard",
        "localized_label": "Standard",
        "index": 1,
        "hidden": false
      }
    },
    {
      "id": "3114",
      "data_type": "FLOAT_TYPE",
      "name": "MRG-Metric-Shared:Minimum Value"
    },
    {
      "id": "1316",
      "data_type": "ENUM_TYPE",
      "name": "MRG-Metric-Shared:OpenScale Category"
    },
    {
      "id": "1317",
      "data_type": "STRING_TYPE",
      "name": "MRG-Metric-Shared:OpenScale Description"
    },
    {
      "id": "1318",
      "data_type": "STRING_TYPE",
      "name": "MRG-Metric-Shared:OpenScale Metric",
      "value": "https://www.ibm.com/cloud/watson-studio"
    },
    {
      "id": "1319",
      "data_type": "STRING_TYPE",
      "name": "MRG-Metric-Shared:OpenScale Metric Value"
    },
    {
      "id": "1322",
      "data_type": "STRING_TYPE",
      "name": "MRG-Metric-Shared:OpenScale Subcategory"
    },
    {
      "id": "1320",
      "data_type": "STRING_TYPE",
      "name": "MRG-Metric-Shared:OpenScale Subscription Name"
    },
    {
      "id": "1321",
      "data_type": "STRING_TYPE",
      "name": "MRG-Metric-Shared:OpenScale Subscription Type"
    },
    {
      "id": "1314",
      "data_type": "FLOAT_TYPE",
      "name": "MRG-Metric-Shared:Red Threshold"
    },
    {
      "id": "3061",
      "data_type": "ENUM_TYPE",
      "name": "MRG-Metric-Shared:Security Category"
    },
    {
      "id": "3062",
      "data_type": "FLOAT_TYPE",
      "name": "MRG-Metric-Shared:Upper Threshold"
    },
    {
      "id": "1313",
      "data_type": "FLOAT_TYPE",
      "name": "MRG-Metric-Shared:Yellow Threshold"
    },
    {
      "id": "1325",
      "data_type": "ENUM_TYPE",
      "name": "MRG-MetricVal:Approve Reject"
    },
    {
      "id": "1323",
      "data_type": "DATE_TYPE",
      "name": "MRG-MetricVal:Expected Collection Date"
    },
    {
      "id": "1324",
      "data_type": "STRING_TYPE",
      "name": "MRG-MetricVal:Metric Owner"
    },
    {
      "id": "1326",
      "data_type": "ENUM_TYPE",
      "name": "MRG-MetricVal:Metric Value Approval Required",
      "value": {
        "id": "4188",
        "name": "No",
        "localized_label": "No",
        "index": 2,
        "hidden": false
      }
    },
    {
      "id": "1327",
      "data_type": "FLOAT_TYPE",
      "name": "MRG-MetricVal:Value",
      "value": 0.75
    },
    {
      "id": "1328",
      "data_type": "DATE_TYPE",
      "name": "MRG-MetricVal:Value Date"
    }
  ],
  "type_definition_id": "77",
  "primary_parent_id": "10210"
}